services:
  imagesentiment:
    build: ./app
    image: imagesentiment:1.0
    container_name: containersentiment
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      
      test: ["CMD-SHELL", "python -c \"import urllib.request; urllib.request.urlopen('http://127.0.0.1:8000/GetHealthy')\" || exit 1"]
      interval: 15s       # Vérifie toutes les 15 secondes
      timeout: 5s         # Laisse 5s à la requête pour aboutir
      retries: 3          # Si ça échoue 3 fois de suite (APRÈS le start_period), le conteneur est "unhealthy"
      start_period: 900s  # Laisse jusqu'à 15 minutes à ton API pour télécharger le modèle
    environment:
      DATABASE_URL: ${DATABASE_URL}
      BASE_URL: ${BASE_URL}
    
    
  ui_site:
    build: ./ui_site
    image: imagesentimentuisite:1.0
    container_name : sentiment_uisite
    ports:
      - "8500:8501"
    depends_on:
    
      imagesentiment: 
        condition: service_healthy

      ui:
        condition: service_started 
      
    environment:
      API_URL: ${API_URL}


  ui:
    build: ./ui
    image: varde11/imagesentimentui:1.0
    container_name: sentiment_ui
    ports:
      - "8501:8501"

    depends_on:
      imagesentiment:
        condition: service_healthy

    environment:
      API_URL: ${API_URL}


  db:
    image: postgres:15
    container_name: sentiment_db
    ports:
      - "5433:5432"
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: sentiment_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d sentiment_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
